#!/bin/bash
#
#  -- Script in Bash --
#
#  Dryncs, Copy files serialized from local pc or remote pc.
#
#    Copyright @ 2023-2024, BIOS Tech <biostech@pc.biosxtreme.net>
#              @ 2024, Erwin Castedo <blkid@protonmail.com>
#
# --------------------------------------------------------------------
#
#  GNU AFFERO GENERAL PUBLIC LICENSE
#     Version 3, 19 November 2007
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#  https://www.gnu.org/licenses/agpl-3.0.txt
#
#===============================================================================
#
#      What is this:
#
#          FILE: dryncs
#
#         USAGE: ./dryncs
#
#   DESCRIPTION: Copy Files Serialized listed from a text file to one local pc o remote pc
#
#       OPTIONS: in config file 'mdialog_conf'
#  REQUIREMENTS: rsync, dialog, bash 5.2, samba server, samba client, lsblk, blkid
#          BUGS: Dialog in the first database update the main menu closed.
#         NOTES: (Linux) For Remote copies add the resources you wanna share to smb.conf, (Windows) Just add the shared resources
#        AUTHOR: Erwin Castedo <blkid@protonmail.com>
#  ORGANIZATION: BIOS Tech <pc.biosxtreme.net>
#       CREATED: 13/07/2024 21:00
#      REVISION: 2.0
#
#===============================================================================
#
# Variable dryncs Config File
#
# Put full path for variables.

# For test this script you can test populating dirs and files with
# populate-dirs-files
# populate-dirs-files-ns2
# just run in console:
#   chmod a+rw populate-dirs-files populate-dirs-files-ns2
#   mkdir /test
#   cd test
#   ./populate-dirs-files
#   ./populate-dirs-files-ns2

###############
#    CONFIG   #
###############

# Origin/Target Paths for copy
#
# if you change the default path, you need
# create this directories and files manually with the same names

# Target and Source path, you can leave in blank. Other example:
# if you have samba moint point, this need to be mounted firsth
# //ip/shared-resource
# or locally with simple slash /
# or to the anywhere

# With dialog you can change the target folder, but you can
# change here with the default target folder if you want.

dialogdest="$HOME/"
dialogdest2="$HOME/"
dialogdest3="$HOME/"

# dialogorig var. This file content the names
# of Music dirs/files to copy, example: Copy a Dirs where i have a identifier
# number like dirM001, dirM002. So you need write this series M001 and M002
# to the other place like a usb memory, the file name doesn't matter.
# Just write line by line in a text for example: i-need-copy-this-dirs.txt
#     M001
#     M002

# Lista de Pedido. Source path/Ruta Origen.
# Navigate and choice by example i-need-copy-this-dirs.txt

dialogorig="$HOME/"

# DATABASE PATHs
# 
# Importante!!! ejecute siempre la 'opción 9 Actualizar Base de Datos' cuando
# haya modificado o aumentado más directorios
#
# Fill with full path, example /path/to/mallrepos

mallrepos="/path-to/dryncsnsx.git/mallrepos"
fallrepos="/path-to/dryncsnsx.git/fallrepos"
callrepos="/path-to/dryncsnsx.git/callrepos"
lallrepos="/path-to/dryncsnsx.git/lallrepos"
jallrepos="/path-to/dryncsnsx.git/jallrepos"
aallrepos="/path-to/dryncsnsx.git/aallrepos"

# REPOSITORY PATH
#
# Source path to directories/Files to copy. If you change the source path
# you need update with 9 option in the program
#
# Ejemplo
# Music Source
# msourcepath="$HOME/Programs/REPO_MUSICA/"
#
# In Cygwin
# fsourcepath="/cygdrive/unidad/REPO_PELICULAS/"
#
# In Linux
# asourcepath="/path/to/REPO_APPS/"

msourcepath="/path/to/M/"
fsourcepath="/path/to/F/"
csourcepath="/path/to/C/"
lsourcepath="/path/to/L/"
jsourcepath="/path/to/J/"
asourcepath="/path/to/A/"

# If you have more things in other place, write the paths here
# you can write 2 paths for every categorie, if you want more, you have the source for write your own code

msourcepath2="/path/to/M2/"
msourcepath3="/path/to/M3/"
fsourcepath2="/path/to/F2/"
fsourcepath3="/path/to/F3/"
fsourcepath4="/path/to/F4/"
fsourcepath5="/path/to/F5/"
fsourcepath6="/path/to/F6/"
fsourcepath7="/path/to/F7/"
fsourcepath8="/path/to/F8/"
fsourcepath9="/path/to/F9/"
fsourcepath10="/path/to/F10/"
csourcepath2="/path/to/C2/"
csourcepath3="/path/to/C3/"
lsourcepath2="/path/to/L2/"
lsourcepath3="/path/to/L3/"
jsourcepath2="/path/to/J2/"
jsourcepath3="/path/to/J3/"
asourcepath2="/path/to/A2/"
asourcepath3="/path/to/A3/"

# Path Logs
#
# Remember put the full path, example /path/to/copiados.log

copiadoslog="/path-to/dryncsnsx.git/copiados.log"

# Log failed Copied

fallidoslog="/path-to/dryncsnsx.git/fallidos.log"

# Log rsync

rsynclog="/path-to/dryncsnsx.git/dryncs.log"

################
#  END CONFIG  #
################
